Issue#542 fix
episphere/biospecimen pull request #415
Opened 2022-09-27 19:29 UTC by we-ai

This PR is to fix issue #542. The followings are details:
- #542 (https://github.com/episphere/connect/issues/542) fix.
- Cleaned up some codes for clarity.

2022-09-28 20:21 UTC, anthonypetersen requested changes
See few comments, we can discuss if necessary. Besides that looks great. Love that we have meaningful variable names now.

2022-09-29 01:01 UTC, we-ai commented on src/fieldToConceptIdMapping.js
> +        accountIdEntered: 148996099,
removed 148996099

2022-09-29 01:02 UTC, we-ai commented on src/fieldToConceptIdMapping.js
> +        idIsManuallyEntered: 387108065,
removed 387108065

2022-09-29 02:53 UTC, Gbarra9 commented on src/shared.js
> +export const specimenCollection = {
In my opinion, I like the constant "specimenCollection" for reference and readability in the getInstituteSpecimensList function found in the events.js file.

https://github.com/episphere/biospecimen/pull/415/files?diff=unified&w=0#diff-aa3209e98840e6d236562086e3c6942a28f0c6beef6897d036367d09cc313c59R691-R710

2022-09-29 02:53 UTC, Gbarra9 approved these changes

2022-09-29 14:12 UTC, anthonypetersen commented on src/shared.js
> +export const specimenCollection = {
> In my opinion, I like the constant "specimenCollection" for reference and readability in the getInstituteSpecimensList function found in the events.js file.
> 
> https://github.com/episphere/biospecimen/pull/415/files?diff=unified&w=0#diff-aa3209e98840e6d236562086e3c6942a28f0c6beef6897d036367d09cc313c59R691-R710

I don't disagree about the readability, my only concern is that if / when we have to add new tubes it's just another place that we have to update constants.

2022-09-30 14:14 UTC, anthonypetersen approved these changes

2022-09-30 14:15 UTC, we-ai commented on src/shared.js
> +export const specimenCollection = {
Moved the constant to tubeValidation.js for easier maintenance.

2022-09-30 14:25 UTC, abhinavjonnada82 approved these changes

2022-09-30 14:59 UTC, merged