BSD: Add daily reports page to Reports tab
episphere/biospecimen pull request #569
Opened 2023-08-16 20:51 UTC by abhinavjonnada82

Title^^
This PR addresses following issue:
-> Table displays list of participants that have checked in & out
-> Participants record are removed from the table after 2 days of check-in
-> Used state management to keep track of API response
-> User can filter based on Collection Location
-> Optimized as required & re-used code

https://github.com/episphere/connect/issues/631

Checklist:
- [X] Code cleanup
- [X] Check for ES Lint warnings
- [X] Verify test cases
- [X] Check for GIT conflicts 
- [ ] Verified unit tests pass with current changes [N/A]
- [ ] Any dependencies or modules  [N/A]
- [X] Attach PoC
- [ ] Add notes

Test Cases Verified with PoC attached: 

1.) On daily reports page, should display list of participants with essential information:
![Screenshot 2023-08-16 at 4 47 13 PM](https://github.com/episphere/biospecimen/assets/30497847/b00b18e0-2b01-4c7e-ba7e-b6e6597bdfd9)

2.) Filter on HP Research Clinic, should return a list of participants:
![Screenshot 2023-08-16 at 4 48 12 PM](https://github.com/episphere/biospecimen/assets/30497847/72c0ff79-dcb3-4e78-a37c-c9774e9ca0b6)

3.) Filter on ALL, should return a list of participants from all locations:
![Screenshot 2023-08-16 at 4 49 07 PM](https://github.com/episphere/biospecimen/assets/30497847/afa6f25b-64c5-4f55-877d-acd8db37e5f4)

4.) For testing purposes only, participant should be removed after 1hr:
Before:
![Screenshot 2023-08-16 at 3 40 44 PM](https://github.com/episphere/biospecimen/assets/30497847/1a665643-446b-45c0-952a-44693311762f)
![Screenshot 2023-08-16 at 3 40 56 PM](https://github.com/episphere/biospecimen/assets/30497847/a3787101-5891-4deb-a0dc-ca77ca6c5fa9)

After: Participant removed
![Screenshot 2023-08-16 at 3 45 57 PM](https://github.com/episphere/biospecimen/assets/30497847/01e782e7-dc35-47d9-adcf-17a760de97e3)

2023-08-18 15:30 UTC, JoeArmani requested changes
Just one small concern on the data site key I marked.

2023-08-21 12:44 UTC, JoeArmani approved these changes
looks good

2023-08-21 14:58 UTC, anthonypetersen commented on src/pages/dailyReport.js
> +                    <li><a class="dropdown-item" data-siteKey="rivEas" id="rivEas">River East</a></li>
feels like this could be automated via looping in the future so we can eliminate extra places that need updates if sites are added.. fine for now

2023-08-21 14:59 UTC, anthonypetersen approved these changes
looks good

2023-08-21 18:14 UTC, merged