BPTL Dashboard: UI for home collection (Part 1)
episphere/biospecimen pull request #609
Opened 2023-10-31 14:11 UTC by abhinavjonnada82

This PR addresses following feature:
https://github.com/episphere/connect/issues/771

Related PR: https://github.com/episphere/connectFaas/pull/448

Checklist:
- [X] Code cleanup
- [X] Check for ES Lint warnings
- [ ] Verify test cases
- [X] Check for GIT conflicts 
- [ ] Verified unit tests pass with current changes [N/A]
- [ ] Any dependencies or modules  [N/A]
- [X] Attach PoC
- [ ] Add notes

PoC:

- Assemble Kit:
<img width="1506" alt="Screenshot 2023-10-31 at 10 08 57 AM" src="https://github.com/episphere/biospecimen/assets/30497847/4419a4ad-2475-4166-8dda-ce6af50a16b2">

- Print Labels:
<img width="1404" alt="Screenshot 2023-10-31 at 10 11 18 AM" src="https://github.com/episphere/biospecimen/assets/30497847/64213c3d-d226-49c0-ac5c-119c9758ec6d">

Notes:

2023-11-01 06:56 UTC, jhflorey approved these changes

2023-11-01 06:56 UTC, jhflorey commented on src/fieldToConceptIdMapping.js
> +
NIT: SHould we remove space line

2023-11-01 06:56 UTC, jhflorey commented on src/pages/homeCollection/printLabels.js
> +import { nonUserNavBar, unAuthorizedUser } from "./../../navbar.js";
`unAuthorizedUser` appears to be unused

2023-11-01 06:56 UTC, jhflorey commented on src/pages/homeCollection/printLabels.js
> +export const printLabelsScreen = async (auth, route) => {
`route` appears be unused

2023-11-01 06:56 UTC, jhflorey commented on src/pages/homeCollection/printLabels.js
> +              const template = `
NIT: Should we assign the string value for alertList.innerHTML without declaring `template`

2023-11-01 15:26 UTC, Gbarra9 approved these changes
Looks good. Left comments.

2023-11-01 15:26 UTC, Gbarra9 commented on src/pages/homeCollection/kitAssembly.js
> +const kitAssemblyTemplate = async (name, auth, route) => {
`auth` and `route` parameters are not being used in `kitAssemblyTemplate`

2023-11-01 15:26 UTC, Gbarra9 commented on src/pages/homeCollection/kitAssembly.js
> +  const a = document.getElementById('saveKit');
We could rename `a` to `saveKitButton` or another variable name to be more descriptive.

2023-11-01 15:26 UTC, Gbarra9 commented on src/pages/homeCollection/kitAssembly.js
> +  if(appState.getState().UKID !== ``) {
```suggestion
  if (appState.getState().UKID !== ``) { 
```
NIT: spacing

2023-11-01 15:26 UTC, Gbarra9 commented on src/pages/homeCollection/kitAssembly.js
> +    if(appState.getState().UKID !== ``) {
```suggestion
    if (appState.getState().UKID !== ``) {
```
NIT: spacing

2023-11-01 15:26 UTC, Gbarra9 commented on src/pages/homeCollection/kitAssembly.js
> +  let a = document.getElementById('dropdownSites');
We can change this variable name `a` to another descriptive name.

2023-11-02 01:30 UTC, jhflorey approved these changes

2023-11-02 02:21 UTC, Gbarra9 approved these changes

2023-11-02 02:21 UTC, Gbarra9 commented on src/shared.js
> +else api = 'http://127.0.0.1:5001/nih-nci-dceg-connect-dev/us-central1/biospecimen?';
I want to confirm if this localhost url is correct?

2023-11-03 14:21 UTC, anthonypetersen requested changes

2023-11-03 14:21 UTC, anthonypetersen commented on src/pages/homeCollection/kitAssembly.js
> +          document.getElementById('scannedBarcode').value = scannedBarcodeValue
are these lines needed? would the values not already be set?

2023-11-03 14:21 UTC, anthonypetersen commented on src/pages/homeCollection/kitAssembly.js
> +      body: JSON.stringify(kitData),
should this be in a function?

2023-11-03 14:46 UTC, anthonypetersen approved these changes

2023-11-03 14:48 UTC, merged